### PR TITLE
Add faker

### PR DESCRIPTION
**Pull request by TylerRockwell**
### Why?
#46 
Because Faker is awesome

### What Changed?
Added faker to Gemfile template

### CODE REVIEW

**Review by dacur — APPROVED** [review]
lol what took so long?!?  😄 👍

**Comment by TylerRockwell** [comment]
Today is the first day in a long time that I'm not completely absorbed by Stilio. 😄

**Comment by TylerRockwell** [comment]
Thanks, @dacur

**Comment by dacur** [comment]
congrats 👏 👏 👏  @TylerRockwell

**Pull request merged**
