### PR TITLE
Configure things to use dotenv

### PR DESCRIPTION
**Pull request by dkniffin**
## Why?

- We should move to using environment variables for secrets instead of gitignoring the secrets file. Environment variables are easier to configure in most environments than editing a file. For more info, see https://12factor.net/config

## What Changed?

- Remove `secrets.yml`from `.gitignore`
- Add a template `secrets.yml` and code to copy it into place
- Add `dotenv-rails` to the Gemfile
- Add a starter `.env` file
- Update specs
- Updated `.travis.yml`

### CODE REVIEW

**Comment by dkniffin** [comment]
A couple more things will need to change on this before merging it:
1) Obviously, resolve the conflicts
2) Remove `cp secrets.example.yml secrets.yml` from `.travis.yml`
3) Add `<<: *default` to the production section of secrets

**Comment by dkniffin** [comment]
Also, we should be gitignoring `.env` and setting up a `.env.example`

**Review by eddwk — APPROVED** [review]
lgtm!

**Comment by dkniffin** [comment]
I'm not sure why this is including some of the things from #128. I say we merge it and if there's issues, I'll fix them.

**Pull request merged**
